export const levels = [
  "A Level",
  "BTEC",
  "GCSE",
  "IB",
  "International A Level (IAL)",
  "NVQ",
  "O Level",
  "Pre-U (Cambridge)",
  "VRQ",
  "iGCSE",
];

export const examBoards = [
  "AQA",
  "OCR",
  "CCEA",
  "Pearson (Edexcel)",
  "WJEC",
  "CAIE",
];

export const subjects = [
  "Accounting",
  "Aeronautical Engineering",
  "Afrikaans",
  "Agriculture",
  "Aircraft Maintenance",
  "Ancient History",
  "Animal Care",
  "Animal Management",
  "Anthropology",
  "Applied Human Biology",
  "Applied Law",
  "Applied Psychology",
  "Applied Science",
  "Arabic",
  "Archaeology",
  "Architecture",
  "Art and Design",
  "Artificial Intelligence",
  "Astronomy",
  "Aviation Operations",
  "Bahasa Indonesia",
  "Beauty Therapy and Hairdressing",
  "Bengali",
  "Biblical Hebrew",
  "Biology",
  "Business",
  "Business Administration",
  "Business Enterprise",
  "Business Studies",
  "Chemistry",
  "Child Development",
  "Childcare",
  "Chinese",
  "Citizenship Studies",
  "Classical Civilisation",
  "Classical Greek",
  "Classical Studies",
  "Classics",
  "Combined Science",
  "Commerce",
  "Computer Science",
  "Computer Science",
  "Computing",
  "Construction and the Built Environment",
  "Contemporary Crafts",
  "Criminology",
  "Critical Thinking",
  "Customer Service Operations",
  "Dance",
  "Design and Technology",
  "Design and Textiles",
  "Development Studies",
  "Digital Media Production",
  "Digital Media and Design",
  "Digital Techonology",
  "Drama",
  "Drama and Theatre",
  "Dutch",
  "Economics",
  "Electronics",
  "Engineering",
  "English - First Language",
  "English Language",
  "English Literature",
  "Environemntal Science",
  "Environmental Management",
  "Environmental Studies",
  "Environmental Technology",
  "Fashion and Textiles",
  "Film Studies",
  "Food Preparation and Nutrition",
  "Food Technology",
  "Food and Textile Technology",
  "French",
  "Further Mathematics",
  "General Studies",
  "Geography",
  "Geology",
  "German",
  "Global Citizenship",
  "Global Development",
  "Global Perspectives",
  "Graphics",
  "Greek",
  "Gujarati",
  "Health, Social Care and Childcare",
  "Hindi",
  "History",
  "History of Art",
  "Home Economics",
  "Horticulture",
  "Hospitality",
  "ICT",
  "IT",
  "Irish",
  "Islamic Studies",
  "Italian",
  "Japanese",
  "Korean",
  "Laboratory Science",
  "Latin",
  "Law",
  "Malay",
  "Marketing",
  "Mathematics",
  "Maths",
  "Media Studies",
  "Modern Hebrew",
  "Music",
  "Music Performance",
  "Music Technology",
  "Pakistan Studies",
  "Performing Arts",
  "Persian",
  "Philosophy",
  "Photography",
  "Physical Education",
  "Physical Science",
  "Physics",
  "Physics",
  "Polish",
  "Politics",
  "Portuguese",
  "Product Design",
  "Psychology",
  "Punjabi",
  "Religious Studies",
  "Retail Operations",
  "Russian",
  "Sanskrit",
  "Sinhala",
  "Sociology",
  "Spanish",
  "Sport",
  "Sports Science",
  "Statistics",
  "Swahili",
  "Tamil",
  "Thai",
  "Travel and Tourism",
  "Turkish",
  "Urdu",
  "Welsh",
  "World Development",
  "World Literature",
];
